version: '3.8'

services:
  auth-api:
    build:
      context: .
      dockerfile: AuthService.API/Dockerfile 
    ports:
      - "5000:8080" # Host:Container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=AuthDb;User Id=sa;Password=admin123!@#;TrustServerCertificate=True;
    networks:
      - svcauth-net

networks:
  svcauth-net:
    external: true
